split: val
print_examples: true # true, false
progress_every: 1
batch_size: 4
max_samples: 500 # set to null to use all samples
report_path: eval_report.json
wandb_log: true # set to true to enable Weights & Biases logging
# Note that you will not be able to download artifacts with `wandb_log` set to false.
metrics:
  - accuracy 